---
title: "Cambridge Parks and Playgrounds"
output: html_document
---
Created for Spatial Analysis Class
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, message=FALSE, echo=FALSE}
library(sf)
library(tidyverse)
library(ggspatial)
library(ggthemes)
library(raster)
```

```{r st_read, message=FALSE, echo=FALSE, results='hide'}

playgrounds <- st_read("playgrounds.geojson")
neighborhoods <- st_read("BOUNDARY_CDDNeighborhoods.shp.zip")
recreations <- st_read("recreation.kml")

```

## Alex's Good Map

```{r cambridge_plot test, echo=FALSE}

cambridge_plot <- ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartodark", alpha = 1) +
  labs(caption = "Generated by Alex Cardelle. Map tiles by Stamen Design. Data by OpenStreetMap") +
geom_sf(data = neighborhoods, lty = 2.5, color = "azure", aes(fill = "Neighborhoods"), alpha = .15) +
geom_sf(data = recreations, color = "cadetblue4",size = 0.25, aes(fill = "Parks"), alpha = .85) +
geom_sf(data = playgrounds, shape = 23, size = 3, fill = "goldenrod", aes(color = "Playgrounds"), alpha = .5) +
scale_color_manual(values = "darkorange", name = "") +
scale_fill_manual(values = c("darkgrey","cadetblue4"), name = "") +
theme_map()

  
cambridge_plot
```

## Alex's Bad Map

```{r eval=TRUE, cambridge_plot , echo=FALSE}

cambridge_plot <- ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw", alpha = 0.25) +
  labs(caption = "Generated by Alex Cardelle. Map tiles by Stamen Design. Data by OpenStreetMap") +
  geom_sf(data = neighborhoods, alpha = 0.25) +
  geom_sf(data = recreations) +
  geom_sf(data = playgrounds, shape = 23, size = 3, aes(fill = "Playgrounds")) +
scale_fill_manual(values = "white", name = "") +
theme_map()

  
cambridge_plot
```
```{r eval=FALSE, color_test, echo=FALSE}

ggplot() +
  geom_sf(data = playgrounds, alpha = 0.5,
          aes(fill = "Historic District")) +
  geom_sf(data = neighborhoods) +
  geom_sf(data = recreations, color = "green") +
  scale_fill_manual(values = "blue", name = "") 

```

## Noah's Good Map

```{r noah, echo=FALSE}

ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight") +
  geom_sf(data = neighborhoods, color = "gray", alpha = 0.05, size = 0.5, lty = 2, aes(fill="Neighborhoods")) +
  geom_sf(data = recreations, color = NA, alpha = 0.5, size = 0, aes(fill="Parks")) +
  geom_sf(data = playgrounds, shape = 16, aes(color = "Playgrounds")) +
  scale_color_manual(values = "darkviolet", name = "") +
  scale_fill_manual(values = c("gray","green"), name = "") +
  labs(caption = "Map generated by Noah Levine, map tiles by Stamen Design, data from the City of Cambridge, and basemap by OpenStreetMap.") +
  theme_map()

```

## Noah's Bad Map

``` {r noahs bad map, echo=FALSE}
ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenwatercolor") +
  geom_sf(data = playgrounds, shape = 13, aes(color = "Playgrounds")) +
  geom_sf(data = recreations, color = NA, alpha = 1, size = 0, aes(fill="Parks")) +
  geom_sf(data = neighborhoods, color = "red", alpha = 0.05, size = 0.5, aes(fill="Neighborhoods")) +
  scale_color_manual(values = "orange", name = "") +
  scale_fill_manual(values = c("gray","lightblue"), name = "") +
  labs(caption = "Map generated by Noah Levine, map tiles by Stamen Design, data from the City of Cambridge, and basemap by OpenStreetMap.") +
  theme_map()

```

## Marina's Good Map

```{r marinas first map, echo=FALSE}

ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight") +
  labs(caption = "Generated by Marina Freitas. Map tiles by Stamen Design. Data by OpenStreetMap.") +
  geom_sf(data = neighborhoods, fill = NA, color = "black", lty = 2, lwd = 0.2) +
  geom_sf(data = recreations, fill = "#4FDE6D", color = NA, alpha = 0.5) +
  geom_sf(data = playgrounds, color = "#F138B6", aes(fill = "playgrounds")) +
  scale_fill_manual(values = "orange", name = "") +
theme_map()

```

## Marina's Bad Map

```{r marinas bad map, echo=FALSE} 

ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw") +
  labs(caption = "Generated by Marina Freitas. Map tiles by Stamen Design. Data by OpenStreetMap.") +
  geom_sf(data = neighborhoods, fill = NA, color = "#E12E2E", lty = 1, lwd = 1) +
  geom_sf(data = recreations, fill = "#2E8DE1", color = NA, alpha = 1) +
  geom_sf(data = playgrounds, color = "#952EE1", aes(fill = "playgrounds")) +
  scale_fill_manual(values = "orange", name = "") +
theme_map()

```

## Livesey's Good Map
```{r Map2, echo=FALSE}

ggplot() + 
  annotation_map_tile(zoomin= 0, progress = "none", type= "hikebike") + 
  geom_sf(data=neighborhoods, color= NA, alpha=0.5, aes(fill="Cambridge Neighborhoods")) + 
  geom_sf(data=recreations, color= NA, alpha=2, aes(fill="Parks")) +
  geom_sf(data=playgrounds, shape=18, size= 2, aes(color= "Playgrounds")) +
scale_fill_manual(values= c("darkgrey", "darkgreen"), name= "") +
scale_color_manual(values= c("lawngreen"), name="") + 
labs(caption= "Map tiles and data by OpenStreetMap")

```

## Livesey's Bad Map
```{r Map1, echo=FALSE}

ggplot() + 
  annotation_map_tile(zoomin= 0, progress = "none", type= "cartolight") + 
  geom_sf(data=neighborhoods, color= NA, alpha=1, aes(fill="Cambridge Neighborhoods")) + 
  geom_sf(data=recreations, color= NA, alpha=1, aes(fill="Parks")) + 
  geom_sf(data=playgrounds, aes(color= "Playgrounds")) +
scale_fill_manual(values= c("darkgrey", "forestgreen"), name= "") + 
scale_color_manual(values= c("black"), name="") +
labs(caption= "Map tiles and data by OpenStreetMap")

```

Produced at the GSD 
